/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    materials: Material;
    'material-details': MaterialDetail;
    categories: Category;
    enrollments: Enrollment;
    transactions: Transaction;
    banks: Bank;
    tenants: Tenant;
    media: Media;
    'hero-sliders': HeroSlider;
    products: Product;
    provinces: Province;
    cities: City;
    districts: District;
    subdistricts: Subdistrict;
    orders: Order;
    reviews: Review;
    discounts: Discount;
    licenses: License;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    'material-details': MaterialDetailsSelect<false> | MaterialDetailsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    banks: BanksSelect<false> | BanksSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'hero-sliders': HeroSlidersSelect<false> | HeroSlidersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    provinces: ProvincesSelect<false> | ProvincesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    districts: DistrictsSelect<false> | DistrictsSelect<true>;
    subdistricts: SubdistrictsSelect<false> | SubdistrictsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    discounts: DiscountsSelect<false> | DiscountsSelect<true>;
    licenses: LicensesSelect<false> | LicensesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('admin' | 'member') | null;
  phone?: string | null;
  dateOfBirth?: string | null;
  avatar?: (number | null) | Media;
  addresses?:
    | {
        label: 'home' | 'office' | 'other';
        fullName: string;
        street: string;
        city: string;
        province: string;
        postalCode: string;
        id?: string | null;
      }[]
    | null;
  subscribedToNewsletter?: boolean | null;
  marketingNotes?: string | null;
  /**
   * Apakah user sudah menyelesaikan validasi Google Form
   */
  gformValidated?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: number;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  thumbnail?: (number | null) | Media;
  /**
   * Izinkan preview tanpa autentikasi
   */
  previewAllowed?: boolean | null;
  /**
   * Memerlukan pembayaran untuk akses penuh
   */
  requiresPurchase?: boolean | null;
  price?: number | null;
  /**
   * Link Google Form untuk validasi (opsional)
   */
  gformLink?: string | null;
  category: number | Category;
  featured?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-details".
 */
export interface MaterialDetail {
  id: number;
  material: number | Material;
  /**
   * Urutan tampil sesi pembelajaran (1, 2, 3, ...)
   */
  order: number;
  title: string;
  type: 'video' | 'pdf' | 'article';
  /**
   * YouTube URL, link PDF, atau konten artikel
   */
  url: string;
  /**
   * Contoh: 15 menit
   */
  duration?: string | null;
  /**
   * Jika dicentang, sesi ini dapat diakses tanpa pembelian
   */
  isFreePreview?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  userId: number | User;
  materialId: number | Material;
  status: 'preview' | 'purchased' | 'completed';
  progress: number;
  enrolledAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  userId: number | User;
  materialId: number | Material;
  amount: number;
  method: 'qris' | 'bank_transfer' | 'midtrans';
  status: 'pending' | 'approved' | 'failed';
  /**
   * Upload payment proof for bank transfer
   */
  proofUrl?: (number | null) | Media;
  bankId?: (number | null) | Bank;
  /**
   * QRIS payment data
   */
  qrisData?: string | null;
  /**
   * Midtrans payment data
   */
  midtransData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  approvalDate?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks".
 */
export interface Bank {
  id: number;
  name: string;
  accountNumber: string;
  accountHolder: string;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  /**
   * Custom theme configuration (colors, fonts, etc.)
   */
  theme?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-sliders".
 */
export interface HeroSlider {
  id: number;
  title: string;
  subtitle?: string | null;
  image: number | Media;
  buttonText?: string | null;
  buttonLink?: string | null;
  active?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Products available in the storefront
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (number | null) | Media;
  images?:
    | {
        image: number | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  price: number;
  compareAtPrice?: number | null;
  sku?: string | null;
  barcode?: string | null;
  trackInventory?: boolean | null;
  stock?: number | null;
  continueSellingWhenOutOfStock?: boolean | null;
  hasVariants?: boolean | null;
  options?:
    | {
        name: string;
        values?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        variantTitle: string;
        sku?: string | null;
        price: number;
        stock?: number | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  shipping?: {
    isPhysicalProduct?: boolean | null;
    weight?: number | null;
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  category?: (number | null) | Category;
  productType?: string | null;
  vendor?: string | null;
  collections?: string | null;
  status: 'draft' | 'active' | 'archived';
  featured?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    urlHandle?: string | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces".
 */
export interface Province {
  id: number;
  name: string;
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  type?: ('Kota' | 'Kabupaten') | null;
  province: number | Province;
  postalCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts".
 */
export interface District {
  id: number;
  name: string;
  city: number | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subdistricts".
 */
export interface Subdistrict {
  id: number;
  name: string;
  district: number | District;
  postalCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  customer: number | User;
  customerEmail?: string | null;
  items?:
    | {
        product?: (number | null) | Product;
        productTitle: string;
        quantity: number;
        unitPrice: number;
        totalPrice: number;
        id?: string | null;
      }[]
    | null;
  checkoutCurrency?: ('IDR' | 'USD' | 'SGD') | null;
  exchangeRateAtCheckout?: number | null;
  subtotal: number;
  discountAmount?: number | null;
  shippingCost?: number | null;
  tax?: number | null;
  total: number;
  paymentStatus?: ('pending' | 'payment_review' | 'paid' | 'failed' | 'refunded') | null;
  fulfillmentStatus?: ('unfulfilled' | 'processing' | 'shipped' | 'completed' | 'complaint') | null;
  paymentMethod?: ('qris' | 'bank_transfer' | 'xendit' | 'cod' | 'other') | null;
  paymentData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  shippingAddress?: {
    fullName?: string | null;
    phone?: string | null;
    province?: string | null;
    city?: string | null;
    district?: string | null;
    subdistrict?: string | null;
    postalCode?: string | null;
    street?: string | null;
    country?: string | null;
  };
  status?: ('pending' | 'paid' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  author: number | User;
  rating: number;
  title: string;
  body: string;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts".
 */
export interface Discount {
  id: number;
  code: string;
  type: 'percentage' | 'fixed';
  value: number;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses".
 */
export interface License {
  id: number;
  key: string;
  tenant: number | Tenant;
  plan?: ('free' | 'pro') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            headline?: string | null;
            subheadline?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            richText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'materials';
        value: number | Material;
      } | null)
    | ({
        relationTo: 'material-details';
        value: number | MaterialDetail;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'banks';
        value: number | Bank;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'hero-sliders';
        value: number | HeroSlider;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'provinces';
        value: number | Province;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'districts';
        value: number | District;
      } | null)
    | ({
        relationTo: 'subdistricts';
        value: number | Subdistrict;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'discounts';
        value: number | Discount;
      } | null)
    | ({
        relationTo: 'licenses';
        value: number | License;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  dateOfBirth?: T;
  avatar?: T;
  addresses?:
    | T
    | {
        label?: T;
        fullName?: T;
        street?: T;
        city?: T;
        province?: T;
        postalCode?: T;
        id?: T;
      };
  subscribedToNewsletter?: T;
  marketingNotes?: T;
  gformValidated?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  thumbnail?: T;
  previewAllowed?: T;
  requiresPurchase?: T;
  price?: T;
  gformLink?: T;
  category?: T;
  featured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "material-details_select".
 */
export interface MaterialDetailsSelect<T extends boolean = true> {
  material?: T;
  order?: T;
  title?: T;
  type?: T;
  url?: T;
  duration?: T;
  isFreePreview?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  userId?: T;
  materialId?: T;
  status?: T;
  progress?: T;
  enrolledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  userId?: T;
  materialId?: T;
  amount?: T;
  method?: T;
  status?: T;
  proofUrl?: T;
  bankId?: T;
  qrisData?: T;
  midtransData?: T;
  approvalDate?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks_select".
 */
export interface BanksSelect<T extends boolean = true> {
  name?: T;
  accountNumber?: T;
  accountHolder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  theme?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-sliders_select".
 */
export interface HeroSlidersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  image?: T;
  buttonText?: T;
  buttonLink?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  price?: T;
  compareAtPrice?: T;
  sku?: T;
  barcode?: T;
  trackInventory?: T;
  stock?: T;
  continueSellingWhenOutOfStock?: T;
  hasVariants?: T;
  options?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  variants?:
    | T
    | {
        variantTitle?: T;
        sku?: T;
        price?: T;
        stock?: T;
        image?: T;
        id?: T;
      };
  shipping?:
    | T
    | {
        isPhysicalProduct?: T;
        weight?: T;
        length?: T;
        width?: T;
        height?: T;
      };
  category?: T;
  productType?: T;
  vendor?: T;
  collections?: T;
  status?: T;
  featured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        urlHandle?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provinces_select".
 */
export interface ProvincesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  province?: T;
  postalCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts_select".
 */
export interface DistrictsSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subdistricts_select".
 */
export interface SubdistrictsSelect<T extends boolean = true> {
  name?: T;
  district?: T;
  postalCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  customerEmail?: T;
  items?:
    | T
    | {
        product?: T;
        productTitle?: T;
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        id?: T;
      };
  checkoutCurrency?: T;
  exchangeRateAtCheckout?: T;
  subtotal?: T;
  discountAmount?: T;
  shippingCost?: T;
  tax?: T;
  total?: T;
  paymentStatus?: T;
  fulfillmentStatus?: T;
  paymentMethod?: T;
  paymentData?: T;
  shippingAddress?:
    | T
    | {
        fullName?: T;
        phone?: T;
        province?: T;
        city?: T;
        district?: T;
        subdistrict?: T;
        postalCode?: T;
        street?: T;
        country?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  author?: T;
  rating?: T;
  title?: T;
  body?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discounts_select".
 */
export interface DiscountsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licenses_select".
 */
export interface LicensesSelect<T extends boolean = true> {
  key?: T;
  tenant?: T;
  plan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              richText?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  appName: string;
  appDescription?: string | null;
  logoUrl?: (number | null) | Media;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  enableRegistration?: boolean | null;
  maintenanceMode?: boolean | null;
  contactEmail?: string | null;
  socialLinks?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  appName?: T;
  appDescription?: T;
  logoUrl?: T;
  primaryColor?: T;
  secondaryColor?: T;
  enableRegistration?: T;
  maintenanceMode?: T;
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}