import type { CollectionConfig } from 'payload'
import { isAdmin, isPublicRead } from '../access/index.ts'

export const Referrals: CollectionConfig = {
  slug: 'referrals',
  admin: {
    useAsTitle: 'referralCode',
    defaultColumns: ['referrer', 'referee', 'referralCode', 'status', 'bonusAwarded', 'createdAt'],
    description: 'Referral program tracking — who invited whom',
    group: 'Marketing',
  },
  access: {
    create: () => true,
    read: isPublicRead,
    update: isAdmin,
    delete: isAdmin,
  },
  fields: [
    {
      name: 'referrer',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      label: 'Referrer (Who Invites)',
      admin: {
        description: 'The member who invited someone',
      },
    },
    {
      name: 'referee',
      type: 'relationship',
      relationTo: 'users',
      required: false,
      label: 'Referee (Who Was Invited)',
      admin: {
        description: 'The new member who was referred',
      },
    },
    {
      name: 'tenant',
      type: 'relationship',
      relationTo: 'tenants',
      required: true,
      label: 'Brand / Tenant',
      admin: {
        description: 'Brand this referral belongs to',
      },
    },
    {
      name: 'referralCode',
      type: 'text',
      required: true,
      label: 'Referral Code Used',
      admin: {
        description: 'The code that was used for this referral',
      },
    },
    {
      name: 'codeGeneratedBy',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      label: 'Code Generated By',
      admin: {
        description: 'The referrer who owns this code',
      },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'pending',
      label: 'Status',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Registered', value: 'registered' },
        { label: 'First Purchase Completed', value: 'completed' },
        { label: 'Expired', value: 'expired' },
        { label: 'Cancelled', value: 'cancelled' },
      ],
    },
    {
      name: 'referrerBonusPoints',
      type: 'number',
      required: false,
      defaultValue: 0,
      label: 'Referrer Bonus Points',
      admin: {
        description: 'Points awarded to referrer when referee completes first purchase',
      },
    },
    {
      name: 'refereeBonusPoints',
      type: 'number',
      required: false,
      defaultValue: 0,
      label: 'Referee Bonus Points',
      admin: {
        description: 'Welcome bonus points for the new member',
      },
    },
    {
      name: 'bonusAwarded',
      type: 'checkbox',
      defaultValue: false,
      label: 'Bonus Awarded',
      admin: {
        description: 'Whether the referral bonus has been credited',
      },
    },
    {
      name: 'bonusAwardedAt',
      type: 'date',
      admin: {
        description: 'When the bonus was credited',
      },
    },
    {
      name: 'firstOrder',
      type: 'relationship',
      relationTo: 'orders',
      required: false,
      label: 'First Order (Completion Trigger)',
      admin: {
        description: 'The order that triggered the referral bonus',
      },
    },
    {
      name: 'referralSource',
      type: 'select',
      required: false,
      label: 'Source',
      options: [
        { label: 'Registration', value: 'registration' },
        { label: 'Checkout', value: 'checkout' },
      ],
    },
    {
      name: 'metadata',
      type: 'json',
    },
  ],
  indexes: [
    {
      fields: { referralCode: 1 },
    },
    {
      fields: { referrer: 1, tenant: 1 },
    },
    {
      fields: { referee: 1 },
    },
    {
      fields: { status: 1 },
    },
  ],
  timestamps: true,
}